// save_sticker.ts - 贴纸收藏插件
// 保存别人或自己发的贴纸到指定贴纸包
// 支持批量模式：每次start生成新贴纸包，连续发送图片自动转贴纸并保存

// @ts-expect-error -- provided by the Classic TeleBox host
import { createDirectoryInAssets } from '@utils/pathHelpers'
// @ts-expect-error -- provided by the Classic TeleBox host
import { Plugin } from '@utils/pluginBase'
// @ts-expect-error -- provided by the Classic TeleBox host
import { getPrefixes } from '@utils/pluginManager'
import * as crypto from 'crypto'
import * as fs from 'fs'
import * as path from 'path'
// @ts-expect-error -- provided by the Classic TeleBox host
import sharp from 'sharp'
// @ts-expect-error -- provided by the Classic TeleBox host
import { Api, type TelegramClient } from 'teleproto'
// @ts-expect-error -- provided by the Classic TeleBox host
import { CustomFile } from 'teleproto/client/uploads'

// 获取命令前缀
const prefixes = getPrefixes()
const mainPrefix = prefixes[0] || '.'
const shortCommandName = `${mainPrefix}ss`

const getErrorMessage = (error: unknown): string => {
  if (error instanceof Error) return error.message
  if (typeof error === 'string') return error
  if (error && typeof error === 'object' && 'message' in error && typeof error.message === 'string') {
    return error.message
  }
  return String(error)
}

const getTelegramError = (error: unknown): string | undefined => {
  if (error && typeof error === 'object' && 'errorMessage' in error && typeof error.errorMessage === 'string') {
    return error.errorMessage
  }
  return undefined
}

// HTML转义
const htmlEscape = (text: string): string =>
  text.replace(
    /[&<>"']/g,
    (m) =>
      ({
        '&': '&amp;',
        '<': '&lt;',
        '>': '&gt;',
        '"': '&quot;',
        "'": '&#x27;'
      })[m] || m
  )

const isImageDocument = (document: Api.Document): boolean => {
  if ((document.mimeType || '').startsWith('image/')) return true
  const fileName = document.attributes?.find((attr) => attr instanceof Api.DocumentAttributeFilename)?.fileName || ''
  return /\.(?:jpe?g|png|webp|gif|bmp|tiff?|avif|heic|heif)$/i.test(fileName)
}

// 帮助文档
const help_text = `📌 <b>贴纸收藏插件</b>

<b>📝 功能：</b>
• 保存别人或自己发的贴纸到贴纸包
• 自动创建贴纸包（首次使用）
• 支持自定义贴纸包名称
• <b>批量模式</b>：可创建新贴纸包，也可使用固定贴纸包

<b>🔧 使用：</b>
• <code>${shortCommandName}</code> - 回复贴纸/图片，保存到<b>固定贴纸包</b>
• <code>${shortCommandName} start</code> - 开始批量收集（需回复第一张贴纸/图片）
• <code>${shortCommandName} start fixed</code> - 使用固定贴纸包开始批量收集
• <code>${shortCommandName} start &lt;ID&gt;</code> - 开始批量收集（添加到指定贴纸包）
• <code>${shortCommandName} stop</code> - 结束批量收集
• <code>${shortCommandName} set &lt;名称&gt;</code> - 设置<b>固定贴纸包</b>名称
• <code>${shortCommandName} show</code> - 查看当前配置
• <code>${shortCommandName} reset</code> - 重置固定贴纸包
• <code>${shortCommandName} help</code> - 显示帮助

<b>💡 两种模式：</b>

<b>1️⃣ 单次保存模式：</b>
• 回复贴纸或图片后发送 <code>${shortCommandName}</code>
• 保存到固定贴纸包（可自定义名称）
• 图片会自动转换为贴纸格式

<b>2️⃣ 批量收集模式：</b>
1. 回复一个贴纸/图片，发送 <code>${shortCommandName} start</code>（创建新贴纸包）
2. 连续发送图片或贴纸（自动保存到贴纸包）
3. 发送 <code>${shortCommandName} stop</code> 结束

或添加到已有贴纸包：
1. 发送 <code>${shortCommandName} start fixed</code> 使用固定贴纸包，或发送 <code>${shortCommandName} start &lt;ID&gt;</code>
2. 连续发送图片或贴纸
3. 发送 <code>${shortCommandName} stop</code> 结束

<b>📌 说明：</b>
• 固定贴纸包：持久保存，除非手动重置
• 批量模式：默认创建新贴纸包，使用 fixed 则保存到固定贴纸包
• 贴纸包名称只能包含字母、数字和下划线
• 图片会自动转换为512x512的webp贴纸格式`

// 配置接口
interface SaveStickerConfig {
  stickerSetShortName: string // 固定贴纸包名称（单次保存模式）
  autoGenerated: boolean
}

const isSaveStickerConfig = (value: unknown): value is SaveStickerConfig => Boolean(value && typeof value === 'object' && 'stickerSetShortName' in value && typeof value.stickerSetShortName === 'string' && 'autoGenerated' in value && typeof value.autoGenerated === 'boolean')

// 批量收集会话状态
interface BatchSession {
  active: boolean
  stopping: boolean
  startTime: number
  count: number
  stickerSetShortName: string // 批量模式专用贴纸包名称
  generation: number
}

class SaveStickerPlugin extends Plugin {
  cleanup(): void {
    this.generation++
    for (const session of this.batchSessions.values()) session.active = false
    for (const timer of this.cleanupTimers) clearTimeout(timer)
    this.batchSessions.clear()
    this.startingSessions.clear()
    this.processingQueues.clear()
    this.ignoredMessageIds.clear()
    this.processingMessageIds.clear()
    this.cleanupTimers.clear()
  }

  description = help_text
  private configPath: string
  private config: SaveStickerConfig
  private generation = 0

  // 批量收集会话管理
  private batchSessions: Map<string, BatchSession> = new Map()
  // 防止同一会话中的多个 start 命令并发创建或覆盖贴纸包
  private startingSessions: Map<string, symbol> = new Map()
  // 处理队列（防止并发）
  private processingQueues: Map<string, Promise<void>> = new Map()
  // 插件内部为了转换图片而临时发出的贴纸消息，必须跳过监听，避免一张图片被计数两次
  private ignoredMessageIds: Set<string> = new Set()
  // 已经进入处理流程的用户消息，防止运行时重复派发同一条媒体消息
  private processingMessageIds: Set<string> = new Set()
  // reload 时必须清理所有延时任务
  private cleanupTimers: Set<ReturnType<typeof setTimeout>> = new Set()

  cmdHandlers: Record<string, (msg: Api.Message, trigger?: Api.Message) => Promise<void>> = {
    save_sticker: this.handleCommand.bind(this),
    ss: this.handleCommand.bind(this)
  }

  // 监听消息处理器（用于批量模式）
  listenMessageHandler?: (msg: Api.Message, options?: { isEdited?: boolean }) => Promise<void>
  listenMessageHandlerIgnoreEdited: boolean = true

  constructor() {
    super()
    const assetsDir = createDirectoryInAssets('save_sticker')
    this.configPath = path.join(assetsDir, 'config.json')
    this.config = {
      stickerSetShortName: '',
      autoGenerated: false
    }
    this.loadConfig()

    // 设置消息监听器
    this.listenMessageHandler = this.handleListenMessage.bind(this)
  }

  private scheduleCleanup(callback: () => void | Promise<void>, delayMs: number): void {
    const timer = setTimeout(() => {
      this.cleanupTimers.delete(timer)
      void Promise.resolve(callback()).catch((error: unknown) => {
        console.error('[save_sticker] 延时清理失败:', error)
      })
    }, delayMs)
    this.cleanupTimers.add(timer)
  }

  private enqueueProcessing(queueKey: string, task: () => Promise<void>): Promise<void> {
    const previous = this.processingQueues.get(queueKey) ?? Promise.resolve()
    const current = previous
      .catch(() => undefined)
      .then(task)
      .finally(() => {
        if (this.processingQueues.get(queueKey) === current) {
          this.processingQueues.delete(queueKey)
        }
      })
    this.processingQueues.set(queueKey, current)
    return current
  }

  private loadConfig() {
    try {
      if (fs.existsSync(this.configPath)) {
        const data = fs.readFileSync(this.configPath, 'utf-8')
        const parsed: unknown = JSON.parse(data)
        if (isSaveStickerConfig(parsed)) {
          this.config = parsed
        } else {
          this.saveConfig()
        }
      } else {
        this.saveConfig()
      }
    } catch (error) {
      console.error('[save_sticker] 加载配置失败:', error)
    }
  }

  private saveConfig() {
    try {
      fs.writeFileSync(this.configPath, JSON.stringify(this.config, null, 2), 'utf-8')
    } catch (error) {
      console.error('[save_sticker] 保存配置失败:', error)
    }
  }

  // 生成8位随机ID
  private generateShortId(): string {
    return crypto.randomBytes(4).toString('hex')
  }

  // 确保有固定贴纸包名称，如果没有则自动生成
  private ensureStickerSetName(): string {
    if (!this.config.stickerSetShortName) {
      const newId = this.generateShortId()
      this.config.stickerSetShortName = `tb_${newId}`
      this.config.autoGenerated = true
      this.saveConfig()
      console.log(`[save_sticker] 自动生成固定贴纸包名称: ${this.config.stickerSetShortName}`)
    }
    return this.config.stickerSetShortName
  }

  // 获取会话ID
  private getSessionId(msg: Api.Message): string {
    const chatId = msg.peerId?.toString() || 'unknown'
    const userId = msg.senderId?.toString() || '0'
    return `${chatId}_${userId}`
  }

  private getMessageDedupeKey(msg: Api.Message): string {
    return `${msg.peerId?.toString() || 'unknown'}_${msg.id}`
  }

  private isCurrentSession(sessionId: string, session: BatchSession): boolean {
    return session.active && session.generation === this.generation && this.batchSessions.get(sessionId) === session
  }

  private ignoreInternalMessage(msg: Api.Message | undefined | null): void {
    if (!msg) return
    const key = this.getMessageDedupeKey(msg)
    this.ignoredMessageIds.add(key)
    this.scheduleCleanup(
      () => {
        this.ignoredMessageIds.delete(key)
      },
      5 * 60 * 1000
    )
  }

  // 主命令处理器
  private async handleCommand(msg: Api.Message): Promise<void> {
    const generation = this.generation
    const client = msg.client
    if (!client) {
      await msg.edit({ text: '❌ 客户端未初始化', parseMode: 'html' })
      return
    }

    // 参数解析
    const lines = msg.text?.trim()?.split(/\r?\n/g) || []
    const parts = lines?.[0]?.split(/\s+/) || []
    const [, ...args] = parts
    const sub = (args[0] || '').toLowerCase()

    try {
      // 帮助命令
      if (sub === 'help' || sub === 'h') {
        await msg.edit({ text: help_text, parseMode: 'html' })
        return
      }

      // 设置固定贴纸包名称
      if (sub === 'set') {
        await this.handleSetStickerName(msg, args.slice(1))
        return
      }

      // 显示当前配置
      if (sub === 'show' || sub === 'config') {
        await this.handleShowConfig(msg)
        return
      }

      // 重置固定贴纸包
      if (sub === 'reset') {
        this.config.stickerSetShortName = ''
        this.config.autoGenerated = false
        this.saveConfig()
        await msg.edit({
          text: '✅ 已重置固定贴纸包配置，下次保存时将自动生成新的贴纸包',
          parseMode: 'html'
        })
        return
      }

      // 批量模式：开始
      if (sub === 'start') {
        await this.handleBatchStart(msg, client, args.slice(1))
        return
      }

      // 批量模式：停止
      if (sub === 'stop') {
        await this.handleBatchStop(msg)
        return
      }

      // 保存贴纸到固定贴纸包（主功能）
      await this.handleSaveStickerAction(msg, client)
    } catch (error: unknown) {
      if (generation !== this.generation) return
      console.error('[save_sticker] 插件执行失败:', error)
      await msg.edit({
        text: `❌ <b>操作失败:</b> ${htmlEscape(getErrorMessage(error) || '未知错误')}`,
        parseMode: 'html'
      })
    }
  }

  private async handleSetStickerName(msg: Api.Message, args: string[]): Promise<void> {
    const newName = args.join('_').replace(/[^a-zA-Z0-9_]/g, '')

    if (!newName) {
      await msg.edit({
        text: `❌ 请提供贴纸包名称\n\n用法: <code>${shortCommandName} set &lt;名称&gt;</code>\n名称只能包含字母、数字和下划线`,
        parseMode: 'html'
      })
      return
    }

    if (newName.length < 3 || newName.length > 64) {
      await msg.edit({
        text: '❌ 贴纸包名称长度必须在3-64个字符之间',
        parseMode: 'html'
      })
      return
    }

    this.config.stickerSetShortName = newName
    this.config.autoGenerated = false
    this.saveConfig()

    await msg.edit({
      text: `✅ <b>固定贴纸包</b>名称已设置为: <code>${htmlEscape(newName)}</code>\n\n🔗 链接: t.me/addstickers/${htmlEscape(newName)}`,
      parseMode: 'html'
    })
  }

  private async handleShowConfig(msg: Api.Message): Promise<void> {
    const currentName = this.config.stickerSetShortName || '未设置（首次保存时自动生成）'
    const isAuto = this.config.autoGenerated ? '（自动生成）' : ''
    const sessionId = this.getSessionId(msg)
    const session = this.batchSessions.get(sessionId)

    let batchInfo = ''
    if (session?.active) {
      batchInfo = `\n\n🔄 <b>批量收集模式:</b> 进行中\n• 贴纸包: <code>${htmlEscape(session.stickerSetShortName)}</code>\n• 已收集: ${session.count} 个\n• 链接: t.me/addstickers/${htmlEscape(session.stickerSetShortName)}`
    }

    await msg.edit({
      text: `📌 <b>贴纸收藏配置</b>\n\n<b>固定贴纸包:</b> <code>${htmlEscape(currentName)}</code> ${isAuto}${batchInfo}\n\n💡 使用 <code>${shortCommandName} set &lt;名称&gt;</code> 修改固定贴纸包`,
      parseMode: 'html'
    })
  }

  // 批量模式：开始
  private async handleBatchStart(msg: Api.Message, client: TelegramClient, args: string[]): Promise<void> {
    const sessionId = this.getSessionId(msg)
    if (this.startingSessions.has(sessionId)) {
      await msg.edit({ text: '⏳ 正在启动批量收集，请稍候…', parseMode: 'html' })
      return
    }

    const startToken = Symbol(sessionId)
    this.startingSessions.set(sessionId, startToken)
    try {
      await this.startBatchSession(msg, client, args)
    } finally {
      if (this.startingSessions.get(sessionId) === startToken) this.startingSessions.delete(sessionId)
    }
  }

  private async startBatchSession(msg: Api.Message, client: TelegramClient, args: string[]): Promise<void> {
    const generation = this.generation
    const sessionId = this.getSessionId(msg)
    const peerId = msg.peerId
    if (!peerId) {
      await msg.edit({ text: '❌ 无法识别当前会话', parseMode: 'html' })
      return
    }

    // 检查是否已有活跃会话
    const existingSession = this.batchSessions.get(sessionId)
    if (existingSession?.active) {
      await msg.edit({
        text: `⚠️ 批量收集模式已在进行中\n\n📦 贴纸包: <code>${htmlEscape(existingSession.stickerSetShortName)}</code>\n📊 已收集: ${existingSession.count} 个\n\n发送图片或贴纸即可自动保存，或发送 <code>${shortCommandName} stop</code> 结束`,
        parseMode: 'html'
      })
      return
    }

    // 获取回复的消息（如果有）
    let replyMsg: Api.Message | null = null
    if (msg.replyTo && 'replyToMsgId' in msg.replyTo && msg.replyTo.replyToMsgId) {
      try {
        const replyMsgId = msg.replyTo.replyToMsgId
        const messages = await client.getMessages(peerId, {
          ids: [replyMsgId]
        })
        if (messages && messages.length > 0) {
          replyMsg = messages[0]
        }
      } catch (error) {
        console.error('[save_sticker] 获取回复消息失败:', error)
      }
    }
    if (generation !== this.generation) return

    // 检查是否指定了固定贴纸包或贴纸包ID
    let batchStickerSetName = ''
    let isUsingExisting = false
    const requestedSet = (args[0] || '').trim()
    const useFixedSet = ['fixed', '固定'].includes(requestedSet.toLowerCase())

    if (useFixedSet) {
      batchStickerSetName = this.ensureStickerSetName()
      try {
        const stickerSet = await client.invoke(
          new Api.messages.GetStickerSet({
            stickerset: new Api.InputStickerSetShortName({ shortName: batchStickerSetName }),
            hash: 0
          })
        )
        if (stickerSet instanceof Api.messages.StickerSet) {
          isUsingExisting = true
        }
      } catch (error: unknown) {
        if (generation !== this.generation) return
        if (getTelegramError(error) !== 'STICKERSET_INVALID') {
          throw error
        }
        // 固定贴纸包尚未创建时，可通过回复第一张贴纸/图片创建
      }
      if (generation !== this.generation) return

      if (!isUsingExisting && !replyMsg?.media) {
        await msg.edit({
          text: `❌ 固定贴纸包尚未创建，请回复一个贴纸或图片后发送 <code>${shortCommandName} start fixed</code>`,
          parseMode: 'html'
        })
        return
      }
    } else if (args.length > 0 && args[0]) {
      // 使用指定的贴纸包ID
      batchStickerSetName = args[0].replace(/[^a-zA-Z0-9_]/g, '')
      if (batchStickerSetName.length < 3 || batchStickerSetName.length > 64) {
        await msg.edit({
          text: '❌ 贴纸包名称长度必须在3-64个字符之间',
          parseMode: 'html'
        })
        return
      }

      // 检查贴纸包是否存在
      try {
        const stickerSet = await client.invoke(
          new Api.messages.GetStickerSet({
            stickerset: new Api.InputStickerSetShortName({ shortName: batchStickerSetName }),
            hash: 0
          })
        )
        if (stickerSet instanceof Api.messages.StickerSet) {
          isUsingExisting = true
        }
      } catch (error: unknown) {
        if (generation !== this.generation) return
        if (getTelegramError(error) === 'STICKERSET_INVALID') {
          await msg.edit({
            text: `❌ 贴纸包 <code>${htmlEscape(batchStickerSetName)}</code> 不存在`,
            parseMode: 'html'
          })
          return
        }
        throw error
      }
      if (generation !== this.generation) return
    } else {
      // 没有指定贴纸包ID，需要回复贴纸/图片来创建新贴纸包
      if (!replyMsg?.media) {
        await msg.edit({
          text: `❌ 请回复一个贴纸或图片来创建新贴纸包\n\n用法: <code>${shortCommandName} start</code>（回复贴纸/图片）\n或: <code>${shortCommandName} start &lt;ID&gt;</code>（添加到指定贴纸包）`,
          parseMode: 'html'
        })
        return
      }

      // 生成新的贴纸包名称
      batchStickerSetName = `tb_batch_${this.generateShortId()}`
    }

    // 获取回复的媒体信息
    let isReplySticker = false
    let isReplyPhoto = false
    let replyDocument: Api.Document | null = null

    if (replyMsg?.media) {
      if (replyMsg.media instanceof Api.MessageMediaDocument) {
        const doc = replyMsg.media.document
        if (doc instanceof Api.Document) {
          isReplySticker = doc.attributes?.some((attr) => attr instanceof Api.DocumentAttributeSticker) || false
          if (isReplySticker) {
            replyDocument = doc
          } else {
            isReplyPhoto = isImageDocument(doc)
          }
        }
      } else if (replyMsg.media instanceof Api.MessageMediaPhoto) {
        isReplyPhoto = true
      }
    }

    // 如果是创建新贴纸包，需要有回复的媒体
    if (!isUsingExisting) {
      if (!isReplySticker && !isReplyPhoto) {
        await msg.edit({
          text: `❌ 回复的内容不是贴纸或图片\n\n请回复一个贴纸或图片来创建新贴纸包`,
          parseMode: 'html'
        })
        return
      }

      await msg.edit({ text: '⏳ 正在创建新贴纸包...', parseMode: 'html' })
      if (generation !== this.generation) return

      try {
        let firstSticker: Api.InputDocument | null = null

        if (isReplySticker && replyDocument) {
          // 贴纸：直接使用
          firstSticker = new Api.InputDocument({
            id: replyDocument.id,
            accessHash: replyDocument.accessHash,
            fileReference: replyDocument.fileReference || Buffer.from([])
          })
        } else if (isReplyPhoto && replyMsg) {
          // 图片：下载并转换
          const buffer = await replyMsg.downloadMedia()
          if (generation !== this.generation) return
          if (!Buffer.isBuffer(buffer)) {
            throw new Error('下载图片失败')
          }

          const stickerBuffer = await sharp(buffer)
            .resize(512, 512, {
              fit: 'contain',
              background: { r: 0, g: 0, b: 0, alpha: 0 }
            })
            .webp({ quality: 90 })
            .toBuffer()
          if (generation !== this.generation) return

          // 先发送贴纸到聊天，获取document
          const sentMsg = await client.sendFile(peerId, {
            workers: 1,
            file: new CustomFile('sticker.webp', stickerBuffer.length, '', stickerBuffer),
            attributes: [
              new Api.DocumentAttributeSticker({
                alt: '⭐',
                stickerset: new Api.InputStickerSetEmpty()
              }),
              new Api.DocumentAttributeFilename({ fileName: 'sticker.webp' })
            ],
            forceDocument: false
          })
          if (generation !== this.generation) {
            await sentMsg?.delete().catch(() => undefined)
            return
          }

          // 从发送的消息中获取document
          this.ignoreInternalMessage(sentMsg)
          if (sentMsg && sentMsg.media instanceof Api.MessageMediaDocument) {
            const doc = sentMsg.media.document as Api.Document
            firstSticker = new Api.InputDocument({
              id: doc.id,
              accessHash: doc.accessHash,
              fileReference: doc.fileReference || Buffer.from([])
            })

            // 删除发送的临时消息
            try {
              await sentMsg.delete()
            } catch {}
          } else {
            throw new Error('发送贴纸失败')
          }
        }

        if (!firstSticker) throw new Error('无法准备第一个贴纸')
        if (generation !== this.generation) return
        const me = await client.getMe()
        if (generation !== this.generation) return
        await client.invoke(
          new Api.stickers.CreateStickerSet({
            userId: me,
            title: batchStickerSetName,
            shortName: batchStickerSetName,
            stickers: [
              new Api.InputStickerSetItem({
                document: firstSticker,
                emoji: '⭐'
              })
            ]
          })
        )
      } catch (createError: unknown) {
        if (generation !== this.generation) return
        console.error('[save_sticker] 创建贴纸包失败:', createError)
        await msg.edit({
          text: `❌ 创建贴纸包失败: ${htmlEscape(getErrorMessage(createError))}`,
          parseMode: 'html'
        })
        return
      }
    } else if (replyMsg?.media && (isReplySticker || isReplyPhoto)) {
      // 指定了已有贴纸包，并且回复了媒体，先添加第一个
      await msg.edit({ text: '⏳ 正在添加到贴纸包...', parseMode: 'html' })
      if (generation !== this.generation) return

      try {
        if (isReplySticker && replyDocument) {
          const documentToAdd = new Api.InputDocument({
            id: replyDocument.id,
            accessHash: replyDocument.accessHash,
            fileReference: replyDocument.fileReference || Buffer.from([])
          })

          if (generation !== this.generation) return
          await client.invoke(
            new Api.stickers.AddStickerToSet({
              stickerset: new Api.InputStickerSetShortName({ shortName: batchStickerSetName }),
              sticker: new Api.InputStickerSetItem({
                document: documentToAdd,
                emoji: '⭐'
              })
            })
          )
        } else if (isReplyPhoto && replyMsg) {
          const buffer = await replyMsg.downloadMedia()
          if (generation !== this.generation) return
          if (!Buffer.isBuffer(buffer)) {
            throw new Error('下载图片失败')
          }

          const stickerBuffer = await sharp(buffer)
            .resize(512, 512, {
              fit: 'contain',
              background: { r: 0, g: 0, b: 0, alpha: 0 }
            })
            .webp({ quality: 90 })
            .toBuffer()
          if (generation !== this.generation) return

          // 先发送贴纸到聊天，获取document
          const sentMsg = await client.sendFile(peerId, {
            workers: 1,
            file: new CustomFile('sticker.webp', stickerBuffer.length, '', stickerBuffer),
            attributes: [
              new Api.DocumentAttributeSticker({
                alt: '⭐',
                stickerset: new Api.InputStickerSetEmpty()
              }),
              new Api.DocumentAttributeFilename({ fileName: 'sticker.webp' })
            ],
            forceDocument: false
          })
          if (generation !== this.generation) {
            await sentMsg?.delete().catch(() => undefined)
            return
          }

          // 从发送的消息中获取document
          this.ignoreInternalMessage(sentMsg)
          if (sentMsg && sentMsg.media instanceof Api.MessageMediaDocument) {
            const doc = sentMsg.media.document as Api.Document
            const documentToAdd = new Api.InputDocument({
              id: doc.id,
              accessHash: doc.accessHash,
              fileReference: doc.fileReference || Buffer.from([])
            })

            if (generation !== this.generation) {
              await sentMsg.delete().catch(() => undefined)
              return
            }
            await client.invoke(
              new Api.stickers.AddStickerToSet({
                stickerset: new Api.InputStickerSetShortName({ shortName: batchStickerSetName }),
                sticker: new Api.InputStickerSetItem({
                  document: documentToAdd,
                  emoji: '⭐'
                })
              })
            )

            // 删除发送的临时消息
            try {
              await sentMsg.delete()
            } catch {}
          } else {
            throw new Error('发送贴纸失败')
          }
        }
      } catch (addError: unknown) {
        if (generation !== this.generation) return
        console.error('[save_sticker] 添加到贴纸包失败:', addError)
        await msg.edit({
          text: `❌ 添加到贴纸包失败: ${htmlEscape(getErrorMessage(addError))}`,
          parseMode: 'html'
        })
        return
      }
    }

    if (generation !== this.generation) return

    // 创建批量收集会话
    const initialCount = isUsingExisting && replyMsg?.media && (isReplySticker || isReplyPhoto) ? 1 : isUsingExisting ? 0 : 1

    this.batchSessions.set(sessionId, {
      active: true,
      stopping: false,
      startTime: Date.now(),
      count: initialCount,
      stickerSetShortName: batchStickerSetName,
      generation
    })

    const statusText = isUsingExisting ? '已连接到现有贴纸包' : '新贴纸包已创建'
    const firstItemText = initialCount > 0 ? `\n✅ 第一个贴纸已保存` : ''

    await msg.edit({
      text:
        `🎯 <b>批量收集模式已开启</b>\n\n` +
        `📦 <b>${statusText}:</b> <code>${htmlEscape(batchStickerSetName)}</code>\n` +
        `🔗 <b>链接:</b> t.me/addstickers/${htmlEscape(batchStickerSetName)}${firstItemText}\n\n` +
        `📸 <b>现在请发送图片或贴纸</b>（会自动保存到贴纸包）\n\n` +
        `⏹️ 发送 <code>${shortCommandName} stop</code> 结束收集`,
      parseMode: 'html'
    })
  }

  // 批量模式：停止
  private async handleBatchStop(msg: Api.Message): Promise<void> {
    const sessionId = this.getSessionId(msg)
    const session = this.batchSessions.get(sessionId)

    if (!session?.active) {
      await msg.edit({
        text: `❌ 批量收集模式未开启\n\n使用 <code>${shortCommandName} start</code> 开始`,
        parseMode: 'html'
      })
      return
    }

    if (session.stopping) {
      await msg.edit({ text: '⏳ 正在等待当前媒体处理完成…', parseMode: 'html' })
      return
    }

    session.stopping = true
    await this.processingQueues.get(sessionId)?.catch(() => undefined)
    if (!this.isCurrentSession(sessionId, session)) return

    session.active = false
    this.batchSessions.delete(sessionId)
    const duration = Math.floor((Date.now() - session.startTime) / 1000)
    const stickerSetName = session.stickerSetShortName

    await msg.edit({
      text: `✅ <b>批量收集已结束</b>\n\n📊 <b>统计:</b>\n• 收集贴纸: ${session.count} 个\n• 用时: ${duration} 秒\n\n📦 <b>贴纸包:</b> <code>${htmlEscape(stickerSetName)}</code>\n🔗 <b>链接:</b> t.me/addstickers/${htmlEscape(stickerSetName)}`,
      parseMode: 'html'
    })
  }

  // 监听消息处理器（批量模式）
  private async handleListenMessage(msg: Api.Message, options?: { isEdited?: boolean }): Promise<void> {
    // 忽略编辑的消息
    if (options?.isEdited) return

    // 检查是否是自己的消息
    if (!msg.out) return

    // 忽略插件内部为了转图片而临时发出的贴纸消息，避免重复保存/重复计数
    const dedupeKey = this.getMessageDedupeKey(msg)
    if (this.ignoredMessageIds.has(dedupeKey)) {
      this.ignoredMessageIds.delete(dedupeKey)
      return
    }

    const sessionId = this.getSessionId(msg)
    const session = this.batchSessions.get(sessionId)

    // 检查是否有活跃的批量会话
    if (!session?.active || session.stopping || session.generation !== this.generation) return

    // 检查是否有媒体
    if (!msg.media) return

    // 判断是图片还是贴纸
    let isPhoto = false
    let isSticker = false

    if (msg.media instanceof Api.MessageMediaPhoto) {
      isPhoto = true
    } else if (msg.media instanceof Api.MessageMediaDocument) {
      const document = msg.media.document
      if (document instanceof Api.Document) {
        isSticker = document.attributes?.some((attr) => attr instanceof Api.DocumentAttributeSticker) || false
        if (!isSticker) isPhoto = isImageDocument(document)
      }
    }

    // 如果既不是图片也不是贴纸，忽略
    if (!isPhoto && !isSticker) return

    if (this.processingMessageIds.has(dedupeKey)) return
    this.processingMessageIds.add(dedupeKey)
    this.scheduleCleanup(
      () => {
        this.processingMessageIds.delete(dedupeKey)
      },
      10 * 60 * 1000
    )

    // 使用队列串行处理，防止并发
    await this.enqueueProcessing(sessionId, async () => {
      const currentSession = this.batchSessions.get(sessionId)
      if (!currentSession?.active || currentSession !== session || currentSession.generation !== this.generation) return
      await this.processStickerMessage(msg, session, isSticker)
    })
  }

  // 处理单个贴纸/图片消息
  private async processStickerMessage(msg: Api.Message, session: BatchSession, isSticker: boolean): Promise<void> {
    const sessionId = this.getSessionId(msg)
    if (!this.isCurrentSession(sessionId, session)) return
    const client = msg.client
    const peerId = msg.peerId
    if (!client || !peerId) return

    // 显示处理中状态
    const processingMsg = await msg.reply({
      message: `⏳ 处理中... (${session.count + 1})`
    })

    try {
      if (!this.isCurrentSession(sessionId, session)) {
        await processingMsg.delete().catch(() => undefined)
        return
      }

      if (isSticker) {
        // 贴纸：直接添加到贴纸包
        const document = (msg.media as Api.MessageMediaDocument).document as Api.Document
        const documentToAdd = new Api.InputDocument({
          id: document.id,
          accessHash: document.accessHash,
          fileReference: document.fileReference || Buffer.from([])
        })

        await client.invoke(
          new Api.stickers.AddStickerToSet({
            stickerset: new Api.InputStickerSetShortName({ shortName: session.stickerSetShortName }),
            sticker: new Api.InputStickerSetItem({
              document: documentToAdd,
              emoji: '⭐'
            })
          })
        )
      } else {
        // 图片：下载并转换为贴纸
        const buffer = await msg.downloadMedia()
        if (!this.isCurrentSession(sessionId, session)) {
          await processingMsg.delete().catch(() => undefined)
          return
        }
        if (!Buffer.isBuffer(buffer)) throw new Error('下载图片失败')

        // 转换为贴纸
        const stickerBuffer = await sharp(buffer)
          .resize(512, 512, {
            fit: 'contain',
            background: { r: 0, g: 0, b: 0, alpha: 0 }
          })
          .webp({ quality: 90 })
          .toBuffer()
        if (!this.isCurrentSession(sessionId, session)) {
          await processingMsg.delete().catch(() => undefined)
          return
        }

        // 先发送贴纸到聊天，获取document
        const sentMsg = await client.sendFile(peerId, {
          workers: 1,
          file: new CustomFile('sticker.webp', stickerBuffer.length, '', stickerBuffer),
          attributes: [
            new Api.DocumentAttributeSticker({
              alt: '⭐',
              stickerset: new Api.InputStickerSetEmpty()
            }),
            new Api.DocumentAttributeFilename({ fileName: 'sticker.webp' })
          ],
          forceDocument: false
        })
        if (!this.isCurrentSession(sessionId, session)) {
          await sentMsg?.delete().catch(() => undefined)
          await processingMsg.delete().catch(() => undefined)
          return
        }

        // 从发送的消息中获取document
        this.ignoreInternalMessage(sentMsg)
        if (sentMsg && sentMsg.media instanceof Api.MessageMediaDocument) {
          const doc = sentMsg.media.document as Api.Document
          const documentToAdd = new Api.InputDocument({
            id: doc.id,
            accessHash: doc.accessHash,
            fileReference: doc.fileReference || Buffer.from([])
          })

          // 添加到批量贴纸包
          await client.invoke(
            new Api.stickers.AddStickerToSet({
              stickerset: new Api.InputStickerSetShortName({ shortName: session.stickerSetShortName }),
              sticker: new Api.InputStickerSetItem({
                document: documentToAdd,
                emoji: '⭐'
              })
            })
          )

          // 删除发送的临时消息
          try {
            await sentMsg.delete()
          } catch {}
        } else {
          throw new Error('发送贴纸失败')
        }
      }

      if (!this.isCurrentSession(sessionId, session)) {
        await processingMsg.delete().catch(() => undefined)
        return
      }

      // 更新计数
      session.count++

      // 删除原消息
      try {
        await msg.delete()
      } catch {}

      // 更新处理中消息为完成
      try {
        await processingMsg.edit({
          text: `✅ 已保存第 ${session.count} 个`,
          parseMode: 'html'
        })
        // 2秒后自动删除完成提示
        this.scheduleCleanup(async () => {
          try {
            await processingMsg.delete()
          } catch {}
        }, 2000)
      } catch {}
    } catch (error: unknown) {
      if (!this.isCurrentSession(sessionId, session)) {
        await processingMsg.delete().catch(() => undefined)
        return
      }
      console.error('[save_sticker] 批量保存失败:', error)

      // 更新处理中消息为失败
      try {
        await processingMsg.edit({
          text: `❌ 保存失败: ${htmlEscape(getErrorMessage(error))}`,
          parseMode: 'html'
        })
      } catch {}
    }
  }

  // 保存单个贴纸/图片到固定贴纸包
  private async handleSaveStickerAction(msg: Api.Message, client: TelegramClient): Promise<void> {
    const generation = this.generation
    const peerId = msg.peerId
    if (!peerId) {
      await msg.edit({ text: '❌ 无法识别当前会话', parseMode: 'html' })
      return
    }
    // 获取回复的消息
    let targetMsg = msg
    if (msg.replyTo && 'replyToMsgId' in msg.replyTo && msg.replyTo.replyToMsgId) {
      try {
        const replyMsgId = msg.replyTo.replyToMsgId
        const messages = await client.getMessages(peerId, {
          ids: [replyMsgId]
        })
        if (messages && messages.length > 0) {
          targetMsg = messages[0]
        }
      } catch (error) {
        console.error('[save_sticker] 获取回复消息失败:', error)
      }
    }
    if (generation !== this.generation) return

    // 检查媒体类型
    if (!targetMsg.media) {
      await msg.edit({
        text: `❌ 请回复一个贴纸或图片\n\n使用方法: 回复贴纸/图片后发送 <code>${shortCommandName}</code>\n\n或使用 <code>${shortCommandName} start</code> 开始批量收集模式`,
        parseMode: 'html'
      })
      return
    }

    // 确保有固定贴纸包名称
    const stickerSetName = this.ensureStickerSetName()

    await msg.edit({ text: '⏳ 正在保存...', parseMode: 'html' })
    if (generation !== this.generation) return

    try {
      // 判断是贴纸还是图片
      let isSticker = false
      let isPhoto = false
      let documentToAdd: Api.InputDocument | null = null

      if (targetMsg.media instanceof Api.MessageMediaDocument) {
        const document = targetMsg.media.document
        if (document instanceof Api.Document) {
          isSticker = document.attributes?.some((attr) => attr instanceof Api.DocumentAttributeSticker)
          if (isSticker) {
            documentToAdd = new Api.InputDocument({
              id: document.id,
              accessHash: document.accessHash,
              fileReference: document.fileReference || Buffer.from([])
            })
          } else {
            isPhoto = isImageDocument(document)
          }
        }
      } else if (targetMsg.media instanceof Api.MessageMediaPhoto) {
        isPhoto = true
      }

      // 如果既不是贴纸也不是图片
      if (!isSticker && !isPhoto) {
        await msg.edit({
          text: `❌ 不支持的媒体类型\n\n请回复贴纸或图片`,
          parseMode: 'html'
        })
        return
      }

      // 如果是图片，需要下载并转换为贴纸
      if (isPhoto) {
        await msg.edit({ text: '⏳ 正在转换图片为贴纸...', parseMode: 'html' })
        if (generation !== this.generation) return

        const buffer = await targetMsg.downloadMedia()
        if (generation !== this.generation) return
        if (!Buffer.isBuffer(buffer)) {
          await msg.edit({ text: '❌ 下载图片失败', parseMode: 'html' })
          return
        }

        // 转换为贴纸格式 (512x512 webp)
        const stickerBuffer = await sharp(buffer)
          .resize(512, 512, {
            fit: 'contain',
            background: { r: 0, g: 0, b: 0, alpha: 0 }
          })
          .webp({ quality: 90 })
          .toBuffer()
        if (generation !== this.generation) return

        // 先发送贴纸到聊天，获取document
        const sentMsg = await client.sendFile(peerId, {
          workers: 1,
          file: new CustomFile('sticker.webp', stickerBuffer.length, '', stickerBuffer),
          attributes: [
            new Api.DocumentAttributeSticker({
              alt: '⭐',
              stickerset: new Api.InputStickerSetEmpty()
            }),
            new Api.DocumentAttributeFilename({ fileName: 'sticker.webp' })
          ],
          forceDocument: false
        })
        if (generation !== this.generation) {
          await sentMsg?.delete().catch(() => undefined)
          return
        }

        // 从发送的消息中获取document
        this.ignoreInternalMessage(sentMsg)
        if (sentMsg && sentMsg.media instanceof Api.MessageMediaDocument) {
          const doc = sentMsg.media.document as Api.Document
          documentToAdd = new Api.InputDocument({
            id: doc.id,
            accessHash: doc.accessHash,
            fileReference: doc.fileReference || Buffer.from([])
          })

          // 删除发送的临时消息
          try {
            await sentMsg.delete()
          } catch {}
          if (generation !== this.generation) return
        } else {
          if (generation !== this.generation) return
          await msg.edit({ text: '❌ 转换贴纸失败', parseMode: 'html' })
          return
        }
      }

      if (!documentToAdd) {
        await msg.edit({ text: '❌ 无法准备贴纸文件', parseMode: 'html' })
        return
      }

      // 检查贴纸包是否存在
      let stickerSetExists = false
      try {
        const stickerSet = await client.invoke(
          new Api.messages.GetStickerSet({
            stickerset: new Api.InputStickerSetShortName({ shortName: stickerSetName }),
            hash: 0
          })
        )
        stickerSetExists = stickerSet instanceof Api.messages.StickerSet
      } catch (error: unknown) {
        if (generation !== this.generation) return
        if (getTelegramError(error) !== 'STICKERSET_INVALID') {
          throw error
        }
      }
      if (generation !== this.generation) return

      if (!stickerSetExists) {
        // 创建新的贴纸包
        const me = await client.getMe()
        if (generation !== this.generation) return
        await client.invoke(
          new Api.stickers.CreateStickerSet({
            userId: me,
            title: stickerSetName,
            shortName: stickerSetName,
            stickers: [
              new Api.InputStickerSetItem({
                document: documentToAdd,
                emoji: '⭐'
              })
            ]
          })
        )
        if (generation !== this.generation) return

        await msg.edit({
          text: `✅ 已创建新贴纸包并保存!\n\n📦 <b>固定贴纸包:</b> <code>${htmlEscape(stickerSetName)}</code>\n🔗 链接: t.me/addstickers/${htmlEscape(stickerSetName)}`,
          parseMode: 'html'
        })
      } else {
        // 添加到现有贴纸包
        await client.invoke(
          new Api.stickers.AddStickerToSet({
            stickerset: new Api.InputStickerSetShortName({ shortName: stickerSetName }),
            sticker: new Api.InputStickerSetItem({
              document: documentToAdd,
              emoji: '⭐'
            })
          })
        )
        if (generation !== this.generation) return

        const mediaType = isPhoto ? '图片' : '贴纸'
        await msg.edit({
          text: `✅ ${mediaType}已保存!\n\n` + `📦 <b>固定贴纸包:</b> <code>${htmlEscape(stickerSetName)}</code>\n` + `🔗 链接: t.me/addstickers/${htmlEscape(stickerSetName)}`,
          parseMode: 'html'
        })
      }
    } catch (error: unknown) {
      if (generation !== this.generation) return
      console.error('[save_sticker] 保存失败:', error)

      let errorMsg = '❌ 保存失败'
      const telegramError = getTelegramError(error)
      if (telegramError === 'STICKERS_TOO_MUCH') {
        errorMsg = '❌ 贴纸包已满（最多50个贴纸）'
      } else if (telegramError === 'STICKERSET_INVALID') {
        errorMsg = '❌ 贴纸包名称无效'
      } else {
        errorMsg = `❌ 保存失败: ${htmlEscape(getErrorMessage(error))}`
      }

      await msg.edit({ text: errorMsg, parseMode: 'html' })
    }
  }
}

export default new SaveStickerPlugin()
